export const inventory = {
  nav: 'Inventory', title: 'Inventory', intro: 'Manage physical stock, reservations, SKU settings, and the permanent movement history.',
  inventoryTab: 'Inventory', historyTab: 'History', totalOnHand: 'Total units on hand', totalAvailable: 'Total available units', reserved: 'Reserved units', lowStock: 'Low-stock SKUs', outOfStock: 'Out-of-stock SKUs', inventoryValue: 'Inventory value',
  search: 'Search product or SKU…', category: 'Category', allCategories: 'All categories', status: 'Status', allStatuses: 'All statuses', inStock: 'In Stock', limited: 'Low Stock', out: 'Out of Stock', inactive: 'Inactive', reservedFilter: 'Reserved inventory', activeFilter: 'Active products',
  product: 'Product', variation: 'Variation', sku: 'SKU', price: 'Price', onHand: 'On hand', available: 'Available', threshold: 'Low-stock threshold', reorder: 'Reorder quantity', lastUpdated: 'Last updated', actions: 'Actions', adjust: 'Adjust stock', settings: 'Settings', bulkSettings: 'Bulk settings', recordSale: 'Record sale', noInventory: 'No SKUs match these filters.',
  adjustTitle: 'Adjust stock', adjustmentType: 'Adjustment type', quantity: 'Quantity', reason: 'Reason', notes: 'Notes (optional)', reference: 'Order or reference number (optional)', currentBalances: 'Current balances', resultingBalances: 'Projected balances', confirm: 'Confirm adjustment', cancel: 'Cancel', saving: 'Saving…', success: 'Inventory updated and movement recorded.', error: 'The inventory transaction failed. Refresh the balances and try again.', invalidProjection: 'This transaction would create an invalid balance.', reasonRequired: 'A reason is required for this adjustment.',
  initial_count: 'Initial stock count', receive: 'Receive inventory', manual_sale: 'Immediate manual sale', reserve: 'Reserve inventory', release: 'Release reservation', fulfillment: 'Fulfill reserved order', damaged: 'Damaged inventory', lost: 'Lost inventory', sample: 'Sample or promotional use', return: 'Customer return', correction: 'Manual correction',
  settingsTitle: 'SKU settings', applySelected: 'Apply to selected SKUs', allowBackorder: 'Allow backorders', active: 'Active SKU', selectRow: 'Select {sku}', selectAtLeastOne: 'Select at least one SKU.', settingsSaved: 'SKU settings saved.',
  recordSaleTitle: 'Record sale or confirmed order', customerName: 'Customer name (optional)', salesChannel: 'Sales channel', orderNumber: 'Order or reference number', orderStatus: 'Status', confirmed: 'Confirmed — reserve stock', immediate_sale: 'Immediate sale — deduct stock', addItem: 'Add item', removeItem: 'Remove item', whatsapp: 'WhatsApp', instagram: 'Instagram', website: 'Website', local_delivery: 'Local delivery', phone: 'Phone', other: 'Other', orderSaved: 'Order recorded and inventory updated.',
  when: 'Timestamp', movement: 'Movement type', onHandChange: 'On-hand change', reservedChange: 'Reserved change', balanceAfter: 'Available after', administrator: 'Administrator', dateFrom: 'From date', dateTo: 'To date', allMovements: 'All movement types', historyEmpty: 'No inventory movements match these filters.', clearFilters: 'Clear filters', loading: 'Loading inventory…', loadError: 'Inventory could not be loaded.', retry: 'Retry',
} as const
