-- Encore Bio Labs CRM MVP schema
-- Paste this file into the Supabase SQL editor for the target project.

create extension if not exists "pgcrypto";

create table if not exists public.crm_campaign_sources (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null unique,
  description text
);

create table if not exists public.crm_leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  first_name text not null default '',
  last_name text not null default '',
  email text not null default '',
  phone text not null default '',
  city text not null default '',
  state text not null default '',
  country text not null default '',
  preferred_language text not null default 'English',
  source text not null default '',
  campaign_source text not null default '',
  interested_products text[] not null default '{}',
  primary_goal text not null default '',
  budget_range text not null default '',
  notes text not null default '',
  status text not null default 'new',
  lead_score integer not null default 0,
  lead_score_explanation jsonb not null default '[]'::jsonb,
  last_contacted_at timestamptz,
  consent_to_contact boolean not null default false,
  research_use_acknowledgment boolean not null default false
);

create table if not exists public.crm_intake_submissions (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  age integer,
  sex text not null default '',
  weight text not null default '',
  height text not null default '',
  main_goal text not null default '',
  current_routine text not null default '',
  sleep_quality text not null default '',
  appetite text not null default '',
  energy text not null default '',
  previous_products_used text not null default '',
  medical_conditions text not null default '',
  medications text not null default '',
  budget text not null default '',
  delivery_city text not null default '',
  preferred_contact_method text not null default '',
  consent_to_contact boolean not null default false,
  research_use_acknowledgment boolean not null default false
);

create table if not exists public.crm_timeline_events (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null default 'manual',
  title text not null default '',
  description text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.crm_notes (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  note text not null,
  created_by text not null default 'admin'
);

create table if not exists public.crm_products_interests (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  product_name text not null,
  category text,
  priority text
);

create index if not exists crm_leads_created_at_idx on public.crm_leads (created_at desc);
create index if not exists crm_leads_status_idx on public.crm_leads (status);
create index if not exists crm_leads_campaign_source_idx on public.crm_leads (campaign_source);
create index if not exists crm_intake_submissions_lead_id_idx on public.crm_intake_submissions (lead_id);
create index if not exists crm_timeline_events_lead_id_idx on public.crm_timeline_events (lead_id);
create index if not exists crm_notes_lead_id_idx on public.crm_notes (lead_id);
create index if not exists crm_products_interests_lead_id_idx on public.crm_products_interests (lead_id);

alter table public.crm_campaign_sources enable row level security;
alter table public.crm_leads enable row level security;
alter table public.crm_intake_submissions enable row level security;
alter table public.crm_timeline_events enable row level security;
alter table public.crm_notes enable row level security;
alter table public.crm_products_interests enable row level security;

-- Public visitors may create a new inquiry and its related submission records,
-- but can never read, update, or delete CRM data. UUIDs are generated by the
-- application and every write is still constrained by table and FK rules.
create policy "public may submit new leads"
  on public.crm_leads for insert to anon with check (
    consent_to_contact = true and research_use_acknowledgment = true
  );
create policy "public may submit intake details"
  on public.crm_intake_submissions for insert to anon with check (
    consent_to_contact = true and research_use_acknowledgment = true
  );
create policy "public may create submission timeline"
  on public.crm_timeline_events for insert to anon with check (
    event_type in ('lead_created', 'intake_submitted')
  );
create policy "public may submit product interests"
  on public.crm_products_interests for insert to anon with check (true);

-- Private CRM access is limited to authenticated users whose app_metadata role
-- was assigned server-side with the Supabase service-role key. Never place the
-- service-role key in Vite or any browser environment variable.
create or replace function public.is_crm_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'crm_admin', false)
$$;

revoke all on function public.is_crm_admin() from public;
grant execute on function public.is_crm_admin() to authenticated;

create policy "admins manage campaign sources" on public.crm_campaign_sources
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());
create policy "admins manage leads" on public.crm_leads
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());
create policy "admins manage intake submissions" on public.crm_intake_submissions
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());
create policy "admins manage timeline events" on public.crm_timeline_events
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());
create policy "admins manage notes" on public.crm_notes
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());
create policy "admins manage product interests" on public.crm_products_interests
  for all to authenticated using (public.is_crm_admin()) with check (public.is_crm_admin());

insert into public.crm_campaign_sources (name, description)
values
  ('Instagram', 'Instagram posts, profile clicks, and DMs'),
  ('WhatsApp', 'WhatsApp inquiries'),
  ('Google', 'Google search or ads'),
  ('Referral', 'Referral from existing customer or partner'),
  ('Website Intake', 'Encore website intake form'),
  ('Catalog', 'Catalog page inquiry'),
  ('Direct', 'Direct website visit'),
  ('Other', 'Other source')
on conflict (name) do nothing;
