import { CheckCircle2, ChevronLeft, ChevronRight } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { usePortalAuth } from '../../context/usePortalAuth'
import { supabase } from '../../lib/supabaseClient'
import { PortalShell } from './PortalShell'

const steps = ['Contact Information','General Profile','Goals','Lifestyle Baseline','Communication Preferences','Agreements','Review & Submit']
const goals = ['Weight-management tracking','Body-composition tracking','Recovery tracking','Energy tracking','Wellness tracking','Research-document access']

export function OnboardingPage() {
  const { identity, refresh } = usePortalAuth()
  const [step,setStep]=useState(0); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState({legalName:identity?.profile.legal_name??'',preferredName:identity?.profile.preferred_name??'',mobile:'',language:'English',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,dateOfBirth:'',height:'',startingWeight:'',currentWeight:'',waist:'',units:'imperial',goals:[] as string[],activity:'',exercise:'',sleep:'',water:'3',appetite:'3',energy:'3',stress:'3',wellness:'3',emailNotifications:true,portalNotifications:true,orderUpdates:true,checkinReminders:true,documentNotifications:true,supportNotifications:true,signature:'',terms:false,privacy:false,ruo:false,noMedical:false,electronic:false,progressData:false,photos:false})
  const update=(name:keyof typeof form,value:string|boolean|string[])=>setForm((current)=>({...current,[name]:value}))
  const toggleGoal=(goal:string)=>update('goals',form.goals.includes(goal)?form.goals.filter((entry)=>entry!==goal):[...form.goals,goal])
  async function submit(event:FormEvent){event.preventDefault();setError('');if(!supabase||!identity)return; if(!(form.terms&&form.privacy&&form.ruo&&form.noMedical&&form.electronic&&form.progressData&&form.signature.trim())){setError('Complete every required acknowledgment and signature.');return} setLoading(true);try{
    const metric=form.units==='metric';const heightCm=metric?Number(form.height):Number(form.height)*2.54;const kg=(value:string)=>metric?Number(value):Number(value)*.453592;const cm=(value:string)=>metric?Number(value):Number(value)*2.54
    const {error:profileError}=await supabase.from('profiles').update({legal_name:form.legalName.trim(),preferred_name:form.preferredName.trim()||null,mobile:form.mobile.trim()||null,preferred_language:form.language,time_zone:form.timeZone}).eq('id',identity.user.id);if(profileError)throw profileError
    const {error:onboardingError}=await supabase.from('onboarding_profiles').upsert({user_id:identity.user.id,date_of_birth:form.dateOfBirth||null,height_cm:heightCm||null,starting_weight_kg:kg(form.startingWeight)||null,current_weight_kg:kg(form.currentWeight)||null,waist_cm:cm(form.waist)||null,preferred_units:form.units,goals:form.goals,activity_level:form.activity,exercise_frequency:form.exercise,average_sleep_hours:Number(form.sleep)||null,water_consistency:Number(form.water),appetite_rating:Number(form.appetite),energy_rating:Number(form.energy),stress_rating:Number(form.stress),wellness_rating:Number(form.wellness),communication_preferences:{email:form.emailNotifications,portal:form.portalNotifications,orders:form.orderUpdates,checkins:form.checkinReminders,documents:form.documentNotifications,support:form.supportNotifications}},{onConflict:'user_id'});if(onboardingError)throw onboardingError
    const {data:versions,error:versionsError}=await supabase.from('consent_versions').select('id,consent_key').eq('active',true);if(versionsError)throw versionsError
    const acceptedKeys=new Set(['terms','privacy','research_use_only','no_medical_advice','electronic_communications','progress_data',...(form.photos?['progress_photos']:[])])
    const records=(versions??[]).filter((entry)=>acceptedKeys.has(entry.consent_key)).map((entry)=>({user_id:identity.user.id,consent_version_id:entry.id,signature_value:form.signature,metadata:{source:'portal_onboarding'}}))
    const {error:consentError}=await supabase.from('consent_acceptances').insert(records);if(consentError)throw consentError
    const {error:submitError}=await supabase.rpc('submit_portal_onboarding');if(submitError)throw submitError
    await refresh();window.location.assign('/portal')
  }catch{setError('Your onboarding submission could not be completed. Review the form and try again.')}finally{setLoading(false)}}
  return <PortalShell><form onSubmit={submit}><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-700">Account onboarding</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">{steps[step]}</h1><div className="mt-7 flex gap-2" aria-label={`Step ${step+1} of ${steps.length}`}>{steps.map((_,index)=><span key={index} className={`h-1.5 flex-1 rounded-full ${index<=step?'bg-teal-600':'bg-slate-200'}`}/>)}</div>
    <div className="mt-9 min-h-[24rem] rounded-[1.5rem] bg-[#f8faf9] p-5 sm:p-8">{step===0?<div className="grid gap-5 sm:grid-cols-2"><Input label="Legal name" value={form.legalName} onChange={(v)=>update('legalName',v)}/><Input label="Preferred name" value={form.preferredName} onChange={(v)=>update('preferredName',v)}/><Input label="Email" value={identity?.profile.email??''} disabled/><Input label="Mobile number" value={form.mobile} onChange={(v)=>update('mobile',v)}/><Select label="Preferred language" value={form.language} onChange={(v)=>update('language',v)} options={['English','Spanish']}/><Input label="Time zone" value={form.timeZone} onChange={(v)=>update('timeZone',v)}/></div>:null}
      {step===1?<div className="grid gap-5 sm:grid-cols-2"><Input label="Date of birth" type="date" value={form.dateOfBirth} onChange={(v)=>update('dateOfBirth',v)}/><Select label="Preferred units" value={form.units} onChange={(v)=>update('units',v)} options={['imperial','metric']}/><Input label={`Height (${form.units==='metric'?'cm':'inches'})`} type="number" value={form.height} onChange={(v)=>update('height',v)}/><Input label={`Starting weight (${form.units==='metric'?'kg':'lb'})`} type="number" value={form.startingWeight} onChange={(v)=>update('startingWeight',v)}/><Input label={`Current weight (${form.units==='metric'?'kg':'lb'})`} type="number" value={form.currentWeight} onChange={(v)=>update('currentWeight',v)}/><Input label={`Waist (${form.units==='metric'?'cm':'inches'})`} type="number" value={form.waist} onChange={(v)=>update('waist',v)}/></div>:null}
      {step===2?<div className="grid gap-3 sm:grid-cols-2">{goals.map((goal)=><button type="button" key={goal} aria-pressed={form.goals.includes(goal)} onClick={()=>toggleGoal(goal)} className={`min-h-14 rounded-xl border p-4 text-left text-sm font-semibold ${form.goals.includes(goal)?'border-teal-700 bg-teal-50':'border-slate-200 bg-white'}`}>{goal}</button>)}</div>:null}
      {step===3?<div className="grid gap-5 sm:grid-cols-2"><Select label="Activity level" value={form.activity} onChange={(v)=>update('activity',v)} options={['Low','Moderate','High']}/><Input label="Exercise sessions per week" value={form.exercise} onChange={(v)=>update('exercise',v)}/><Input label="Average sleep hours" type="number" value={form.sleep} onChange={(v)=>update('sleep',v)}/>{(['water','appetite','energy','stress','wellness'] as const).map((key)=><Select key={key} label={`${key[0].toUpperCase()+key.slice(1)} rating`} value={form[key]} onChange={(v)=>update(key,v)} options={['1','2','3','4','5']}/>)}</div>:null}
      {step===4?<div className="grid gap-3 sm:grid-cols-2">{([['emailNotifications','Email notifications'],['portalNotifications','Portal notifications'],['orderUpdates','Order updates'],['checkinReminders','Check-in reminders'],['documentNotifications','Document notifications'],['supportNotifications','Support notifications']] as const).map(([key,label])=><Check key={key} label={label} checked={form[key]} onChange={(value)=>update(key,value)}/>)}</div>:null}
      {step===5?<div className="grid gap-3">{([['terms','Terms of Service'],['privacy','Privacy Notice'],['ruo','Research Use Only acknowledgment'],['noMedical','No-medical-advice acknowledgment'],['electronic','Electronic communication consent'],['progressData','Progress-data consent'],['photos','Optional progress-photo consent']] as const).map(([key,label])=><Check key={key} label={label} checked={form[key]} onChange={(value)=>update(key,value)}/>)}<Input label="Electronic signature (legal name)" value={form.signature} onChange={(v)=>update('signature',v)}/></div>:null}
      {step===6?<div><CheckCircle2 size={36} className="text-teal-700"/><h2 className="mt-5 text-2xl font-semibold">Review your submission</h2><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><Summary label="Name" value={form.legalName}/><Summary label="Units" value={form.units}/><Summary label="Goals" value={form.goals.join(', ')||'None selected'}/><Summary label="Language" value={form.language}/><Summary label="Notifications" value={form.portalNotifications?'Portal enabled':'Portal disabled'}/><Summary label="Signature" value={form.signature||'Required'}/></dl><p className="mt-6 text-sm leading-6 text-slate-600">Submitting changes your account to pending review. Encore will review the information and acknowledgments before activating portal access.</p></div>:null}</div>
    {error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}<div className="mt-6 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep((value)=>value-1)} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-slate-200 px-5 text-sm font-semibold disabled:opacity-40"><ChevronLeft size={16}/>Back</button>{step<steps.length-1?<button type="button" onClick={()=>setStep((value)=>value+1)} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#071724] px-6 text-sm font-semibold text-white">Continue<ChevronRight size={16}/></button>:<button disabled={loading} className="min-h-12 rounded-full bg-teal-700 px-7 text-sm font-semibold text-white disabled:opacity-50">{loading?'Submitting…':'Submit for review'}</button>}</div>
  </form></PortalShell>
}

function Input({label,value,onChange,type='text',disabled=false}:{label:string;value:string;onChange?:(value:string)=>void;type?:string;disabled?:boolean}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input className="portal-input" type={type} value={value} disabled={disabled} onChange={(event)=>onChange?.(event.target.value)}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<select className="portal-input" value={value} onChange={(event)=>onChange(event.target.value)}><option value="">Select</option>{options.map((option)=><option key={option}>{option}</option>)}</select></label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex min-h-12 items-start gap-3 rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="mt-1 size-4 accent-teal-700"/>{label}</label>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-4"><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-800">{value}</dd></div>}
