import { CheckCircle2, ChevronLeft, ChevronRight } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { usePortalAuth } from '../../context/usePortalAuth'
import { useLocale, useTranslation } from '../../i18n/LocaleContext'
import { supabase } from '../../lib/supabaseClient'
import { PortalShell } from './PortalShell'

export function OnboardingPage() {
  const { identity, refresh } = usePortalAuth()
  const { path, locale } = useLocale()
  const { t } = useTranslation('portal')
  const steps = [t('stepContact'), t('stepProfile'), t('stepGoals'), t('stepLifestyle'), t('stepCommunication'), t('stepAgreements'), t('stepReview')]
  const goals = [t('goalWeight'), t('goalBodyComp'), t('goalRecovery'), t('goalEnergy'), t('goalWellness'), t('goalDocuments')]
  const [step,setStep]=useState(0); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState({legalName:identity?.profile.legal_name??'',preferredName:identity?.profile.preferred_name??'',mobile:'',language:locale === 'es' ? 'Spanish' : 'English',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,dateOfBirth:'',height:'',startingWeight:'',currentWeight:'',waist:'',units:'imperial',goals:[] as string[],activity:'',exercise:'',sleep:'',water:'3',appetite:'3',energy:'3',stress:'3',wellness:'3',emailNotifications:true,portalNotifications:true,orderUpdates:true,checkinReminders:true,documentNotifications:true,supportNotifications:true,signature:'',terms:false,privacy:false,ruo:false,noMedical:false,electronic:false,progressData:false,photos:false})
  const update=(name:keyof typeof form,value:string|boolean|string[])=>setForm((current)=>({...current,[name]:value}))
  const toggleGoal=(goal:string)=>update('goals',form.goals.includes(goal)?form.goals.filter((entry)=>entry!==goal):[...form.goals,goal])
  async function submit(event:FormEvent){event.preventDefault();setError('');if(!supabase||!identity)return; if(!(form.terms&&form.privacy&&form.ruo&&form.noMedical&&form.electronic&&form.progressData&&form.signature.trim())){setError(t('errorAcknowledgments'));return} setLoading(true);try{
    const metric=form.units==='metric';const heightCm=metric?Number(form.height):Number(form.height)*2.54;const kg=(value:string)=>metric?Number(value):Number(value)*.453592;const cm=(value:string)=>metric?Number(value):Number(value)*2.54
    const {error:profileError}=await supabase.from('profiles').update({legal_name:form.legalName.trim(),preferred_name:form.preferredName.trim()||null,mobile:form.mobile.trim()||null,preferred_language:form.language,time_zone:form.timeZone}).eq('id',identity.user.id);if(profileError)throw profileError
    const {error:onboardingError}=await supabase.from('onboarding_profiles').upsert({user_id:identity.user.id,date_of_birth:form.dateOfBirth||null,height_cm:heightCm||null,starting_weight_kg:kg(form.startingWeight)||null,current_weight_kg:kg(form.currentWeight)||null,waist_cm:cm(form.waist)||null,preferred_units:form.units,goals:form.goals,activity_level:form.activity,exercise_frequency:form.exercise,average_sleep_hours:Number(form.sleep)||null,water_consistency:Number(form.water),appetite_rating:Number(form.appetite),energy_rating:Number(form.energy),stress_rating:Number(form.stress),wellness_rating:Number(form.wellness),communication_preferences:{email:form.emailNotifications,portal:form.portalNotifications,orders:form.orderUpdates,checkins:form.checkinReminders,documents:form.documentNotifications,support:form.supportNotifications}},{onConflict:'user_id'});if(onboardingError)throw onboardingError
    const {data:versions,error:versionsError}=await supabase.from('consent_versions').select('id,consent_key').eq('active',true);if(versionsError)throw versionsError
    const acceptedKeys=new Set(['terms','privacy','research_use_only','no_medical_advice','electronic_communications','progress_data',...(form.photos?['progress_photos']:[])])
    const records=(versions??[]).filter((entry)=>acceptedKeys.has(entry.consent_key)).map((entry)=>({user_id:identity.user.id,consent_version_id:entry.id,signature_value:form.signature,metadata:{source:'portal_onboarding'}}))
    const {error:consentError}=await supabase.from('consent_acceptances').insert(records);if(consentError)throw consentError
    const {error:submitError}=await supabase.rpc('submit_portal_onboarding');if(submitError)throw submitError
    await refresh();window.location.assign(path('/portal'))
  }catch{setError(t('errorSubmission'))}finally{setLoading(false)}}
  const unitLabel=(cmOrKg:'height'|'weight'|'waist')=>{
    if(cmOrKg==='height') return form.units==='metric'?t('unitCm'):t('unitInches')
    if(cmOrKg==='waist') return form.units==='metric'?t('unitCm'):t('unitInches')
    return form.units==='metric'?t('unitKg'):t('unitLb')
  }
  return <PortalShell><form onSubmit={submit}><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-700">{t('accountOnboarding')}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">{steps[step]}</h1><div className="mt-7 flex gap-2" aria-label={t('stepAriaLabel',{step:step+1,total:steps.length})}>{steps.map((_,index)=><span key={index} className={`h-1.5 flex-1 rounded-full ${index<=step?'bg-teal-600':'bg-slate-200'}`}/>)}</div>
    <div className="mt-9 min-h-[24rem] rounded-[1.5rem] bg-[#f8faf9] p-5 sm:p-8">{step===0?<div className="grid gap-5 sm:grid-cols-2"><Input label={t('legalNameLabel')} value={form.legalName} onChange={(v)=>update('legalName',v)}/><Input label={t('preferredNameLabel')} value={form.preferredName} onChange={(v)=>update('preferredName',v)}/><Input label={t('emailLabel')} value={identity?.profile.email??''} disabled/><Input label={t('mobileLabel')} value={form.mobile} onChange={(v)=>update('mobile',v)}/><Select label={t('preferredLanguageLabel')} value={form.language} onChange={(v)=>update('language',v)} options={[{value:'English',label:t('languageEnglish')},{value:'Spanish',label:t('languageSpanish')}]} placeholder={t('selectPlaceholder')}/><Input label={t('timeZoneLabel')} value={form.timeZone} onChange={(v)=>update('timeZone',v)}/></div>:null}
      {step===1?<div className="grid gap-5 sm:grid-cols-2"><Input label={t('dateOfBirthLabel')} type="date" value={form.dateOfBirth} onChange={(v)=>update('dateOfBirth',v)}/><Select label={t('preferredUnitsLabel')} value={form.units} onChange={(v)=>update('units',v)} options={[{value:'imperial',label:t('unitImperial')},{value:'metric',label:t('unitMetric')}]} placeholder={t('selectPlaceholder')}/><Input label={t('heightLabel',{unit:unitLabel('height')})} type="number" value={form.height} onChange={(v)=>update('height',v)}/><Input label={t('startingWeightLabel',{unit:unitLabel('weight')})} type="number" value={form.startingWeight} onChange={(v)=>update('startingWeight',v)}/><Input label={t('currentWeightLabel',{unit:unitLabel('weight')})} type="number" value={form.currentWeight} onChange={(v)=>update('currentWeight',v)}/><Input label={t('waistLabel',{unit:unitLabel('waist')})} type="number" value={form.waist} onChange={(v)=>update('waist',v)}/></div>:null}
      {step===2?<div className="grid gap-3 sm:grid-cols-2">{goals.map((goal)=><button type="button" key={goal} aria-pressed={form.goals.includes(goal)} onClick={()=>toggleGoal(goal)} className={`min-h-14 rounded-xl border p-4 text-left text-sm font-semibold ${form.goals.includes(goal)?'border-teal-700 bg-teal-50':'border-slate-200 bg-white'}`}>{goal}</button>)}</div>:null}
      {step===3?<div className="grid gap-5 sm:grid-cols-2"><Select label={t('activityLevelLabel')} value={form.activity} onChange={(v)=>update('activity',v)} options={[{value:'Low',label:t('activityLow')},{value:'Moderate',label:t('activityModerate')},{value:'High',label:t('activityHigh')}]} placeholder={t('selectPlaceholder')}/><Input label={t('exerciseSessionsLabel')} value={form.exercise} onChange={(v)=>update('exercise',v)}/><Input label={t('averageSleepLabel')} type="number" value={form.sleep} onChange={(v)=>update('sleep',v)}/>
        <Select label={t('waterRatingLabel')} value={form.water} onChange={(v)=>update('water',v)} options={['1','2','3','4','5']} placeholder={t('selectPlaceholder')}/>
        <Select label={t('appetiteRatingLabel')} value={form.appetite} onChange={(v)=>update('appetite',v)} options={['1','2','3','4','5']} placeholder={t('selectPlaceholder')}/>
        <Select label={t('energyRatingLabel')} value={form.energy} onChange={(v)=>update('energy',v)} options={['1','2','3','4','5']} placeholder={t('selectPlaceholder')}/>
        <Select label={t('stressRatingLabel')} value={form.stress} onChange={(v)=>update('stress',v)} options={['1','2','3','4','5']} placeholder={t('selectPlaceholder')}/>
        <Select label={t('wellnessRatingLabel')} value={form.wellness} onChange={(v)=>update('wellness',v)} options={['1','2','3','4','5']} placeholder={t('selectPlaceholder')}/>
      </div>:null}
      {step===4?<div className="grid gap-3 sm:grid-cols-2">{([['emailNotifications',t('emailNotificationsLabel')],['portalNotifications',t('portalNotificationsLabel')],['orderUpdates',t('orderUpdatesLabel')],['checkinReminders',t('checkinRemindersLabel')],['documentNotifications',t('documentNotificationsLabel')],['supportNotifications',t('supportNotificationsLabel')]] as const).map(([key,label])=><Check key={key} label={label} checked={form[key]} onChange={(value)=>update(key,value)}/>)}</div>:null}
      {step===5?<div className="grid gap-3">{([['terms',t('ackTerms')],['privacy',t('ackPrivacy')],['ruo',t('ackRuo')],['noMedical',t('noMedicalAck')],['electronic',t('electronicConsentAck')],['progressData',t('progressDataConsent')],['photos',t('progressPhotoConsent')]] as const).map(([key,label])=><Check key={key} label={label} checked={form[key]} onChange={(value)=>update(key,value)}/>)}<Input label={t('signatureLabel')} value={form.signature} onChange={(v)=>update('signature',v)}/></div>:null}
      {step===6?<div><CheckCircle2 size={36} className="text-teal-700"/><h2 className="mt-5 text-2xl font-semibold">{t('reviewSubmission')}</h2><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><Summary label={t('reviewName')} value={form.legalName}/><Summary label={t('reviewUnits')} value={form.units==='metric'?t('unitMetric'):t('unitImperial')}/><Summary label={t('reviewGoals')} value={form.goals.join(', ')||t('reviewGoalsNone')}/><Summary label={t('reviewLanguage')} value={form.language==='Spanish'?t('languageSpanish'):t('languageEnglish')}/><Summary label={t('reviewNotifications')} value={form.portalNotifications?t('reviewNotificationsEnabled'):t('reviewNotificationsDisabled')}/><Summary label={t('reviewSignature')} value={form.signature||t('reviewSignatureRequired')}/></dl><p className="mt-6 text-sm leading-6 text-slate-600">{t('reviewSubmitNote')}</p></div>:null}</div>
    {error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}<div className="mt-6 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep((value)=>value-1)} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-slate-200 px-5 text-sm font-semibold disabled:opacity-40"><ChevronLeft size={16}/>{t('back')}</button>{step<steps.length-1?<button type="button" onClick={()=>setStep((value)=>value+1)} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#071724] px-6 text-sm font-semibold text-white">{t('continueButton')}<ChevronRight size={16}/></button>:<button disabled={loading} className="min-h-12 rounded-full bg-teal-700 px-7 text-sm font-semibold text-white disabled:opacity-50">{loading?t('submitting'):t('submitForReview')}</button>}</div>
  </form></PortalShell>
}

function Input({label,value,onChange,type='text',disabled=false}:{label:string;value:string;onChange?:(value:string)=>void;type?:string;disabled?:boolean}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input className="portal-input" type={type} value={value} disabled={disabled} onChange={(event)=>onChange?.(event.target.value)}/></label>}
type SelectOption = string | { value: string; label: string }
function Select({label,value,onChange,options,placeholder}:{label:string;value:string;onChange:(value:string)=>void;options:SelectOption[];placeholder:string}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<select className="portal-input" value={value} onChange={(event)=>onChange(event.target.value)}><option value="">{placeholder}</option>{options.map((option)=>{const item=typeof option==='string'?{value:option,label:option}:option;return <option key={item.value} value={item.value}>{item.label}</option>})}</select></label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex min-h-12 items-start gap-3 rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="mt-1 size-4 accent-teal-700"/>{label}</label>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-4"><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-800">{value}</dd></div>}
