import { LegalPageLayout, type LegalSection } from './LegalPageLayout'
import { useLocale } from '../../i18n/LocaleContext'

const copy = {
  en: { title: 'Privacy Policy', intro: 'This Privacy Policy explains what information Encore Bio Labs collects, how it is used, and the choices you have.', sections: [['1. Information we collect','When you use research intake, contact us, or place an order, we may collect contact details, research-interest responses, order and shipping details, and basic technical data.'],['2. How we use information','We use information to respond to inquiries, process orders, route research-interest intake for internal review, fulfill shipping, and improve the Site. We do not use intake information to provide medical advice, diagnosis, or treatment.'],['3. Data storage and security','We use reasonable administrative and technical safeguards. No storage or transmission method is completely secure, and absolute security cannot be guaranteed.'],['4. Third-party sharing','We do not sell personal information. We may share information with service providers that operate the Site under confidentiality obligations, or as required by law.'],['5. Your rights','You may request access to, correction of, or deletion of personal information through the research intake process. Additional rights may apply under local privacy law.'],['6. Cookies and analytics','The Site may use cookies or similar technology for functionality and analytics. You can control cookies through your browser settings.'],['7. Children’s privacy','The Site is not directed to individuals under 18, and we do not knowingly collect information from children.'],['8. Changes to this policy','We may update this Privacy Policy. Material changes will be reflected by an updated effective date.'],['9. Contact','Privacy questions or requests can be sent through the research intake process.']] },
  es: { title: 'Política de Privacidad', intro: 'Esta Política de Privacidad explica qué información recopila Encore Bio Labs, cómo la utiliza y qué opciones tienes.', sections: [['1. Información que recopilamos','Al usar la admisión de investigación, contactarnos o realizar un pedido, podemos recopilar datos de contacto, respuestas de interés científico, información de pedido y envío, y datos técnicos básicos.'],['2. Cómo usamos la información','Usamos la información para responder consultas, procesar pedidos, enviar las admisiones para revisión interna, gestionar envíos y mejorar el Sitio. No usamos la información de admisión para ofrecer consejo, diagnóstico o tratamiento médico.'],['3. Almacenamiento y seguridad','Aplicamos medidas administrativas y técnicas razonables. Ningún método de almacenamiento o transmisión es completamente seguro y no podemos garantizar seguridad absoluta.'],['4. Compartición con terceros','No vendemos información personal. Podemos compartirla con proveedores que operan el Sitio bajo obligaciones de confidencialidad o cuando la ley lo exige.'],['5. Tus derechos','Puedes solicitar acceso, corrección o eliminación de tu información personal mediante la admisión de investigación. La legislación local puede otorgar derechos adicionales.'],['6. Cookies y analítica','El Sitio puede usar cookies o tecnologías similares para funciones básicas y analítica. Puedes controlarlas desde la configuración de tu navegador.'],['7. Privacidad de menores','El Sitio no está dirigido a menores de 18 años y no recopilamos conscientemente información de niños.'],['8. Cambios a esta política','Podemos actualizar esta Política de Privacidad. Los cambios importantes se reflejarán con una fecha de vigencia actualizada.'],['9. Contacto','Las preguntas o solicitudes de privacidad pueden enviarse mediante la admisión de investigación.']] },
} as const

export function PrivacyPage() { const { locale } = useLocale(); const page = copy[locale]; const sections: LegalSection[] = page.sections.map(([heading, body]) => ({ heading, body: <p>{body}</p> })); return <LegalPageLayout title={page.title} effectiveDate={locale === 'es' ? '7 de julio de 2026' : 'July 7, 2026'} intro={page.intro} sections={sections} /> }
