import type { crm as crmEn } from '../en/crm'

export const crm: Record<keyof typeof crmEn, string> = {
  statusNew: 'Nuevo', statusContacted: 'Contactado', statusQualified: 'Calificado', statusConsultationRequested: 'Consulta solicitada', statusConverted: 'Convertido', statusLost: 'Perdido',
  salesWorkspace: 'Espacio de ventas', websitePipeline: 'Pipeline de leads del website', whatsappDesk: 'Mesa de calificación de WhatsApp',
  websiteIntro: 'Revisa intakes, puntuación, productos de interés, notas y actividad de seguimiento.', whatsappIntro: 'Revisa conversaciones bilingües, calificación, pendientes, intervención humana y borradores de seguimiento.',
  deskNavigation: 'Áreas del CRM de ventas', websiteLeads: 'Leads del website', whatsapp: 'WhatsApp', supabaseRequired: 'Supabase es obligatorio para acceder al CRM.',
  loadingRecords: 'Cargando leads del website…', recordCount: '{count} registros de leads', autoRefresh: 'Revisión en vivo cada 30 segundos', lastSynced: 'Última revisión {time}', refresh: 'Actualizar', exportCsv: 'Exportar CSV', loadingData: 'Cargando datos del CRM…',
  loadErrorTitle: 'No se pudieron cargar los datos del CRM.', loadErrorFallback: 'No se pudieron cargar los leads del website.', retry: 'Reintentar', syncWarning: 'Falló la última actualización automática. Los registros existentes siguen visibles.',
  emptyTitle: 'Todavía no hay leads del website.', emptyCopy: 'Las nuevas solicitudes del intake público aparecerán aquí automáticamente.', openIntake: 'Abrir intake',
  totalLeads: 'Leads totales', newThisWeek: 'Leads nuevos esta semana', highIntent: 'Leads de alta intención', followUpNeeded: 'Requieren seguimiento',
  followUpQueueEyebrow: 'Cola prioritaria', followUpQueueTitle: 'Leads que necesitan seguimiento humano', followUpQueueCopy: 'Incluye todo lead activo nunca contactado y los activos sin contacto registrado durante 72 horas.', followUpQueueClear: 'La cola de seguimiento está al día.',
  neverContacted: 'Nunca contactado', lastContacted: 'Último contacto {date}', openLead: 'Abrir lead', requestedProducts: 'Productos más solicitados', leadsByCity: 'Leads por ciudad', leadsBySource: 'Leads por origen', recentIntakes: 'Intakes recientes', latestInquiries: 'Solicitudes de investigación más recientes',
  leadTable: 'Tabla de leads', pipeline: 'Pipeline', searchPlaceholder: 'Buscar nombre, correo o teléfono', filterStatus: 'Estado', filterProduct: 'Producto de interés', filterCity: 'Ciudad', filterSource: 'Origen', filterSort: 'Ordenar por puntuación', all: 'Todos', sortHigh: 'Mayor primero', sortLow: 'Menor primero',
  columnLead: 'Lead', columnStatus: 'Estado', columnScore: 'Puntuación', columnProducts: 'Productos', columnCity: 'Ciudad', columnSource: 'Origen', columnCreated: 'Creado', noContact: 'Sin datos de contacto', noFilterMatches: 'Ningún lead coincide con estos filtros.',
  leadDetail: 'Detalle del lead', closeDetails: 'Cerrar detalle del lead', noEmail: 'Sin correo', noPhone: 'Sin teléfono', preferredLanguage: 'Idioma preferido: {language}', leadScore: 'Puntuación del lead', source: 'Origen',
  notes: 'Notas internas', notePlaceholder: 'Agrega una nota duradera para el próximo seguimiento', saveNote: 'Guardar nota', saving: 'Guardando…', noteSaved: 'La nota se guardó en el historial del lead.', noteHistory: 'Historial de notas guardadas', noteHistoryEmpty: 'Todavía no hay notas internas guardadas.',
  markContacted: 'Registrar contacto ahora', markingContacted: 'Registrando…', contactRecorded: 'Contacto registrado. El temporizador de seguimiento se reinició.', contactHelp: 'Úsalo únicamente después de llamar, enviar un correo o escribirle al lead.', lastContactNever: 'Todavía no hay contacto registrado', actionError: 'No se pudo guardar el cambio en el CRM. Inténtalo de nuevo.',
  generateFollowUp: 'Generar seguimiento', writesIn: 'Escribe en {language}', generateWhatsapp: 'Generar borrador de WhatsApp', generateEmail: 'Generar borrador de correo', writing: 'Redactando…', draftError: 'No se pudo generar el borrador de seguimiento.', draftEdit: 'Borrador — edítalo antes de enviarlo', copy: 'Copiar', country: 'País', countryCodeLabel: 'Código de país del teléfono de este lead', openWhatsapp: 'Abrir WhatsApp a +{number}', openEmail: 'Abrir correo a {email}',
  sendDisclaimer: 'Nada se envía automáticamente. Revisa el borrador antes de enviarlo.', noDialablePhone: 'Este lead no dejó un teléfono válido.', verifyCountryCode: 'El intake no confirmó el código de país; verifícalo antes de enviar.',
  templates: 'Plantillas de seguimiento', copyWhatsapp: 'Copiar seguimiento de WhatsApp', copyInstagram: 'Copiar mensaje de Instagram', copyEmail: 'Copiar seguimiento por correo', interestedProducts: 'Productos de interés', noProducts: 'No hay productos de interés registrados.', scoreExplanation: 'Explicación de la puntuación', intakeAnswers: 'Respuestas del intake', noIntake: 'No hay un intake adjunto.', timeline: 'Línea de tiempo', noTimeline: 'Todavía no hay actividad registrada.', notProvided: 'No proporcionado', yes: 'Sí', no: 'No',
  statusChanged: 'Estado cambiado a {status}', contactEvent: 'Contacto manual registrado', contactEventDescription: 'Un operador confirmó que completó un seguimiento.', noteAdded: 'Nota interna agregada', templateCopied: 'Seguimiento de {channel} copiado', templateCopiedDescription: 'Plantilla copiada para revisión y envío manual.', draftCopied: 'Borrador de seguimiento copiado', whatsappOpened: 'WhatsApp abierto con el borrador', emailOpened: 'Correo abierto con el borrador', draftUsedDescription: 'Borrador asistido por IA, revisado por un operador antes de enviarlo.',
  dashboardAlertTitle: '{count} leads del website requieren seguimiento', dashboardAlertCopy: 'Estos leads están activos y nunca fueron contactados, o su último contacto registrado fue hace más de 72 horas.', dashboardAlertAction: 'Trabajar la cola del CRM', dashboardQuickMeta: '{count} requieren seguimiento', dashboardAttentionDetail: 'Leads, soporte, solicitudes, inbox, checkout y revisiones de WhatsApp',
}
