export const inventory = {
  nav: 'Inventario', title: 'Inventario', intro: 'Administra existencias físicas, reservas, ajustes por SKU y el historial permanente de movimientos.',
  inventoryTab: 'Inventario', historyTab: 'Historial', totalOnHand: 'Unidades físicas totales', totalAvailable: 'Unidades disponibles', reserved: 'Unidades reservadas', lowStock: 'SKU con pocas existencias', outOfStock: 'SKU agotados', inventoryValue: 'Valor del inventario',
  search: 'Buscar producto o SKU…', category: 'Categoría', allCategories: 'Todas las categorías', status: 'Estado', allStatuses: 'Todos los estados', inStock: 'Disponible', limited: 'Pocas existencias', out: 'Agotado', inactive: 'Inactivo', reservedFilter: 'Inventario reservado', activeFilter: 'Productos activos',
  product: 'Producto', variation: 'Variación', sku: 'SKU', price: 'Precio', onHand: 'Existencias', available: 'Disponible', threshold: 'Umbral bajo', reorder: 'Cantidad a reordenar', lastUpdated: 'Última actualización', actions: 'Acciones', adjust: 'Ajustar inventario', settings: 'Configuración', bulkSettings: 'Configuración masiva', recordSale: 'Registrar venta', noInventory: 'Ningún SKU coincide con estos filtros.',
  adjustTitle: 'Ajustar inventario', adjustmentType: 'Tipo de ajuste', quantity: 'Cantidad', reason: 'Motivo', notes: 'Notas (opcional)', reference: 'Pedido o referencia (opcional)', currentBalances: 'Saldos actuales', resultingBalances: 'Saldos proyectados', confirm: 'Confirmar ajuste', cancel: 'Cancelar', saving: 'Guardando…', success: 'Inventario actualizado y movimiento registrado.', error: 'La transacción falló. Actualiza los saldos e inténtalo de nuevo.', invalidProjection: 'Esta transacción produciría un saldo no válido.', reasonRequired: 'Este ajuste requiere un motivo.',
  initial_count: 'Conteo inicial', receive: 'Recibir inventario', manual_sale: 'Venta manual inmediata', reserve: 'Reservar inventario', release: 'Liberar reserva', fulfillment: 'Completar pedido reservado', damaged: 'Inventario dañado', lost: 'Inventario perdido', sample: 'Muestra o promoción', return: 'Devolución del cliente', correction: 'Corrección manual',
  settingsTitle: 'Configuración del SKU', applySelected: 'Aplicar a los SKU seleccionados', allowBackorder: 'Permitir pedidos pendientes', active: 'SKU activo', selectRow: 'Seleccionar {sku}', selectAtLeastOne: 'Selecciona al menos un SKU.', settingsSaved: 'Configuración guardada.',
  recordSaleTitle: 'Registrar venta o pedido confirmado', customerName: 'Nombre del cliente (opcional)', salesChannel: 'Canal de venta', orderNumber: 'Número de pedido o referencia', orderStatus: 'Estado', confirmed: 'Confirmado — reservar inventario', immediate_sale: 'Venta inmediata — descontar inventario', addItem: 'Agregar artículo', removeItem: 'Quitar artículo', whatsapp: 'WhatsApp', instagram: 'Instagram', website: 'Sitio web', local_delivery: 'Entrega local', phone: 'Teléfono', other: 'Otro', orderSaved: 'Pedido registrado e inventario actualizado.',
  when: 'Fecha y hora', movement: 'Tipo de movimiento', onHandChange: 'Cambio físico', reservedChange: 'Cambio reservado', balanceAfter: 'Disponible después', administrator: 'Administrador', dateFrom: 'Desde', dateTo: 'Hasta', allMovements: 'Todos los movimientos', historyEmpty: 'Ningún movimiento coincide con estos filtros.', clearFilters: 'Limpiar filtros', loading: 'Cargando inventario…', loadError: 'No se pudo cargar el inventario.', retry: 'Reintentar',
} as const
