import { useMemo, useState } from 'react'
import { Archive, Check, MailOpen, Search, Trash2 } from 'lucide-react'
import { adminFetchCommunications, adminUpdateCommunication, type CommunicationMessage } from '../../../lib/portal/portalData'
import { LoadState, useAsync, useDateFormatter } from '../sections/shared'

const folders = ['inbox', 'sent', 'drafts', 'contact', 'spam', 'trash'] as const
export function AdminCommunications({ contactOnly = false }: { contactOnly?: boolean }) {
  const [mailbox, setMailbox] = useState<string>(contactOnly ? 'contact' : 'inbox'), [search, setSearch] = useState(''), [page, setPage] = useState(0), [active, setActive] = useState<CommunicationMessage | null>(null)
  const params = useMemo(() => ({ mailbox: contactOnly ? 'contact' : mailbox, contactOnly, search, page }), [mailbox, contactOnly, search, page])
  const { data, loading, error, reload } = useAsync(() => adminFetchCommunications(params), [params.mailbox, params.contactOnly, params.search, params.page])
  const date = useDateFormatter()
  async function update(id: string, changes: Parameters<typeof adminUpdateCommunication>[1]) { await adminUpdateCommunication(id, changes); setActive(null); reload() }
  function exportCsv() { const rows = data?.rows ?? []; const csv = ['Name,Email,Phone,Subject,Date,Status,Assigned To', ...rows.map((row) => [row.sender_name,row.sender_email,row.sender_phone ?? '',row.subject,row.created_at,row.status,row.assigned_to ?? ''].map((value) => `"${String(value).replaceAll('"','""')}"`).join(','))].join('\n'); const href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = href; link.download = 'encore-customer-messages.csv'; link.click(); URL.revokeObjectURL(href) }
  return <div className="mt-8 grid gap-5 lg:grid-cols-[13rem_1fr]">
    {!contactOnly && <aside className="rounded-2xl bg-slate-50 p-3">{folders.map((folder) => <button key={folder} onClick={() => { setMailbox(folder); setPage(0) }} className={`flex w-full rounded-xl px-3 py-2 text-left text-sm font-semibold capitalize ${mailbox === folder ? 'bg-[#071724] text-white' : 'text-slate-600 hover:bg-white'}`}>{folder === 'contact' ? 'Contact Form Messages' : folder}</button>)}</aside>}
    <section><div className="flex flex-wrap gap-3"><label className="relative min-w-[15rem] flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(0) }} placeholder="Search sender or subject" className="portal-input w-full pl-10" /></label>{contactOnly && <button onClick={exportCsv} className="rounded-xl border px-4 text-sm font-semibold">Export CSV</button>}</div>
      <LoadState loading={loading} error={error} onRetry={reload}>{data?.rows.length ? <div className="mt-4 overflow-hidden rounded-2xl border border-slate-900/10"><table className="w-full min-w-[44rem] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">From</th><th className="p-3">Subject</th><th className="p-3">Date</th><th className="p-3">Status</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} onClick={() => { setActive(row); if (!row.is_read) void update(row.id, { is_read: true }) }} className={`cursor-pointer border-t border-slate-900/8 hover:bg-teal-50/40 ${row.is_read ? '' : 'font-semibold bg-slate-50/60'}`}><td className="p-3">{row.sender_name || row.sender_email}<span className="block font-normal text-slate-500">{row.sender_email}</span></td><td className="p-3">{row.subject}</td><td className="p-3 text-slate-500">{date(row.created_at, true)}</td><td className="p-3 capitalize">{row.status}</td></tr>)}</tbody></table></div> : <p className="mt-6 rounded-2xl bg-slate-50 p-6 text-sm text-slate-500">No messages in this folder.</p>}
      {data && data.count > 25 && <div className="mt-4 flex justify-end gap-2"><button disabled={!page} onClick={() => setPage(page-1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Previous</button><button disabled={(page+1)*25 >= data.count} onClick={() => setPage(page+1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Next</button></div>}</LoadState>
      {active && <div className="mt-5 rounded-2xl border border-teal-200 bg-teal-50 p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{active.subject}</p><p className="text-sm text-slate-600">{active.sender_name} · {active.sender_email}</p></div><button onClick={() => setActive(null)}>×</button></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6">{active.body_text}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => void update(active.id, { status: 'completed' })} className="inline-flex items-center gap-1 rounded-lg bg-[#071724] px-3 py-2 text-sm font-semibold text-white"><Check size={15}/>Complete</button><button onClick={() => void update(active.id, { mailbox: 'archive' })} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Archive size={15}/>Archive</button><button onClick={() => void update(active.id, { is_read: !active.is_read })} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><MailOpen size={15}/>{active.is_read ? 'Unread' : 'Read'}</button><button onClick={() => void update(active.id, { mailbox: 'trash' })} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Trash2 size={15}/>Delete</button></div></div>}</section>
  </div>
}
